---
- name: Set up environment for ansible-bender (before reboot)
  hosts: all
  vars:
    test_mode: no  # yes - test in CI, no - build an image
    project_dir: /src
    with_tests: no  # yes - run test suite
    with_bender_install: yes
    docker_package_name: docker
    ansible_bender:
      target_image:
        workging_dir: /src
        cmd: /entry.sh
      working_container:
        volumes:
        - "{{ playbook_dir }}:/src"
  tasks:
  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest
    when: with_tests == "yes"
  - name: "figure out docker package name: F31+ has moby, not docker"
    set_fact:
      docker_package_name: moby-engine
    when: ansible_distribution_major_version >= '31'
  - name: use cgroups v1
    lineinfile:
      state: present
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\")^(?!systemd.unified)(.+)"
      # double escape is yaml's fault
      line: "\\1systemd.unified_cgroup_hierarchy=0 \\2"
      backrefs: yes
    become: true
  - name: regen grub config
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    become: true
  - name: Install all packages needed to hack on ab.
    dnf:
      name:
      - git
      - make
      - python3-pip
      - python3-setuptools
      - python3-setuptools_scm
      - python3-setuptools_scm_git_archive
      - python3-wheel  # for bdist_wheel
      - containers-common
      - buildah
      - podman
      - ansible
      - python3-pytest
      - python3-pytest-cov
      - python3-flexmock
      - python3-ipdb
      - python3-jsonschema
      - python3-tabulate
      - '{{ docker_package_name }}'  # one test uses it
      state: present
  # - name: Change storage driver to vfs (ovl on ovl doesn't work)
  #   lineinfile:
  #     path: /etc/containers/storage.conf
  #     regexp: '^driver = '
  #     line: 'driver = "vfs"'
  - name: Change storage driver graphroot to /tmp/containers
    lineinfile:
      path: /etc/containers/storage.conf
      regexp: '^graphroot = '
      line: 'graphroot = "/tmp/containers"'
    when: with_tests == "no"
  - name: copy libpod.conf
    copy:
      src: /usr/share/containers/libpod.conf
      dest: /etc/containers/libpod.conf
      remote_src: yes
    when: with_tests == "no"
  - name: Change cgroup driver to cgroupfs.
    lineinfile:
      path: /etc/containers/libpod.conf
      regexp: '^cgroup_manager = '
      line: 'cgroup_manager = "cgroupfs"'
    when: with_tests == "no"

