downstream_package_name: ansible-bender
specfile_path: ansible-bender.spec
upstream_package_name: ansible-bender
current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
  trigger: pull_request
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: master
